//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDS_TITLECAPTION                1
#define IDS_FILEVERSION                 2
#define IDS_APPCOPYRIGHT                3
#define IDC_IP_UP                       3
#define IDS_REGISTRYKEY                 4
#define IDC_HOST_UP                     4
#define IDS_STRING5                     5
#define IDC_HANDCURSOR                  100
#define IDI_MAIN                        101
#define IDD_MAIN                        102
#define IDI_PASSWORD                    102
#define IDD_NETLOGO                     103
#define IDB_TREE_CONFIG_PROPPAGE        116
#define IDB_BITMAP1                     118
#define IDI_STOPPED                     119
#define IDI_RUNNING                     120
#define IDB_BITMAP3                     140
#define IDR_MENU1                       141
#define IDR_MAINMENU                    141
#define IDD_DIALOG1                     142
#define IDD_LISTCONFIG                  142
#define IDR_MENU2                       145
#define IDD_SETPASSWORD                 147
#define IDB_TREE_CONFIG_AUTH            148
#define IDB_BITMAP2                     151
#define IDB_BITMAP4                     152
#define IDD_DIALOG2                     155
#define IDD_ROUTE                       155
#define IDR_MENU3                       157
#define IDD_DIALOG3                     158
#define IDD_ROUTE_ADVANCED              158
#define IDD_CONNECT                     163
#define IDD_CONFIG_MIMETYPES_ITEM1      164
#define IDD_CONFIG_GENERICLIST1         165
#define IDD_CONFIG_IPFILTERS_ITEM1      191
#define IDD_ROUTE_IPBINDING             191
#define IDD_MONITORROUTE                192
#define IDD_ROUTE_ROUTING               193
#define IDD_ROUTE_ROUTINGS              196
#define IDD_ROUTE_IPBINDINGS            197
#define IDD_ROUTE_HEADERS               198
#define IDD_ROUTE_BASIC                 199
#define IDD_ROUTE_IPBINDING1            200
#define IDD_ROUTE_HEADER                200
#define IDD_ROUTE_LOADBALANCE           201
#define IDD_ROUTE_ADVANCED1             202
#define IDD_ROUTE_THREADING             202
#define IDC_TEXTBOX                     1000
#define IDC_NETLINK                     1000
#define IDC_OK                          1001
#define IDC_CANCEL                      1002
#define IDC_STATICTEXT                  1003
#define IDC_ABOUTICON                   1004
#define IDC_APPNAME                     1005
#define IDC_APPVERSION                  1006
#define IDC_APPCOPYRIGHT                1007
#define IDC_OKBUTTON                    1008
#define IDC_BUILDTIMEDATE               1009
#define IDC_GLLOGO                      1010
#define IDC_SITES                       1011
#define IDC_LIST1                       1012
#define IDC_DETAIL                      1012
#define IDC_PWDWEIGHT                   1012
#define IDC_CHECK1                      1013
#define IDC_AUTOSTART                   1013
#define IDC_ENABLED                     1013
#define IDC_REMOTEADMIN                 1013
#define IDC_PERSISTBYIP                 1013
#define IDC_CONFIGTITLE                 1014
#define IDC_BUTTON2                     1016
#define IDC_BLURB                       1016
#define IDC_DELETE3                     1019
#define IDC_EDIT2                       1021
#define IDC_CHECK2                      1021
#define IDC_IP_LISTENONALL              1021
#define IDC_IPDESCR                     1021
#define IDC_NAME2                       1022
#define IDC_EDIT3                       1022
#define IDC_PASSWORD                    1022
#define IDC_IPADDRESSLIST               1022
#define IDC_DELETE_IP2                  1023
#define IDC_HOST_LIST                   1023
#define IDC_IPADDRESS                   1024
#define IDC_HEADER_NAME                 1025
#define IDC_BUTTON1                     1026
#define IDC_PASSWORD2                   1026
#define IDC_IPADDRESS3                  1026
#define IDC_HEADER_METHOD               1026
#define IDC_BUTTON3                     1027
#define IDC_PASSWORD1                   1027
#define IDC_HEADER_METHOD2              1027
#define IDC_CHECK3                      1033
#define IDC_EDIT7                       1046
#define IDC_GRAPH                       1047
#define IDC_EDIT1                       1050
#define IDC_HOST                        1050
#define IDC_NAME                        1050
#define IDC_PERSISTENCETIME             1050
#define IDC_HEADER_TEXT                 1050
#define IDC_DESCR                       1051
#define IDC_PORT                        1051
#define IDC_LOCALPORT                   1052
#define IDC_REMOTEPORT                  1053
#define IDC_REMOTEHOST                  1054
#define IDC_MAXCONNECTIONS              1055
#define IDC_TOPFRAME                    1056
#define IDC_BUFFERSIZE                  1056
#define IDC_INITBUFFERSIZE              1056
#define IDC_INITIALBUFFERSIZE           1056
#define IDC_USERNAME                    1057
#define IDC_IDLETIMEOUT                 1057
#define IDC_SERVICESTATUS               1058
#define IDC_ORPHANTIMEOUT               1058
#define IDC_DataPumpSpawnThreshold      1058
#define IDC_BUFFERSIZE3                 1058
#define IDC_INITBUFFERSIZE2             1059
#define IDC_MAXBUFFERSIZE               1059
#define IDC_BUFFERSIZE2                 1059
#define IDC_DATAPUMPTHREADS             1059
#define IDC_RESOLVERTHREADS             1060
#define IDC_ResolverSpawnThreshold      1061
#define IDC_DataPumpSpawnThreshold2     1061
#define IDC_COMBO1                      1062
#define IDC_HOST_BALANCE                1062
#define IDC_IP_DOWN                     1064
#define IDC_IP_ADD                      1065
#define IDC_ROUTE                       1065
#define IDC_ROUTENAME                   1065
#define IDC_IP_DELETE                   1066
#define IDC_SOURCEPORT                  1066
#define IDC_TARGETPORT                  1067
#define IDC_HOST_ADD                    1067
#define IDC_TARGETHOST                  1068
#define IDC_HOST_DELETE                 1068
#define IDC_LOADBALANCEMETHOD           1068
#define IDC_CURRENTCONNECTIONS          1069
#define IDC_HOST_DOWN                   1069
#define IDC_TOTALCONNECTIONS            1070
#define IDC_TOTALTRANSFERRED            1071
#define IDC_TRANSFERRATE                1072
#define IDC_HEADER_LIST                 1073
#define IDC_HEADER_ADD                  1074
#define IDC_HEADER_DELETE               1075
#define IDC_HEADER_UP                   1076
#define IDC_HEADER_DOWN                 1077
#define TAB_CONTROL_1                   1079
#define IDC_TABCONTROL                  1079
#define IDC_HEADER_VERBS                1080
#define IDC_HEADER_DESCR                1081
#define IDC_LBMPERSISTBYIP              1082
#define ID_FILE_EXIT                    40001
#define ID_HELP_ABOUT                   40002
#define ID_HELP_PRE                     40003
#define ID_SERVICE_RESTART              40007
#define ID_FILE_CONNECTTO               40008
#define ID_FILE_DISC                    40009
#define ID_SETTINGS_SERVERSETTINGS      40010
#define ID_SETTINGS_WEBSITESETTINGS     40011
#define ID_SERVER_RESTARTSERVERSETTINGS 40012
#define ID_SERVER_RESTARTWEBSITESETTINGS 40013
#define ID_SETTINGS_ADD                 40014
#define ID_SETTINGS_ADDREMOVE_WEBSITES  40015
#define ID_SERVER_SETTINGS              40016
#define ID_SERVER_ADDROUTE              40017
#define ID_SERVER_ADDNEWROUTE           40018
#define ID_SERVER_RESTARTSERVER         40019
#define ID_SERVER_SETPASSWORD           40020
#define ID_SERVER_SERVICECONSOLE        40023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         40024
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
